version: '3.8'

services:
  postgres:
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres -p 5432 -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    depends_on:
      - postgres
    command: [ "sh", "-c", "python app/main.py" ]

volumes:
  postgres_data: